In [3]:
# Messy CSV → Clean AI-Ready Data
# Portfolio Project by Sudhakar

import pandas as pd
import numpy as np
from IPython.display import display

# Better table display
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 100)

print("=== Step 1: Creating a Messy Sample Dataset ===")

# Creating intentional messy data
data = {
    'Customer Name': ['  John Doe ', 'jane smith', 'ALICE WONDER', 'Bob  ', 'John Doe', np.nan, 'Charlie'],
    'Email': ['john@email.com', 'JANE@EMAIL.COM', 'alice@email', 'bob@email.com', 'john@email.com', 'test@test.com', None],
    'Age': ['25', 'thirty', '28', '35', '25', '40', '22'],
    'Purchase Amount': ['$1,200.50', '850', '2,300.00', 'unknown', '1200.5', '950.75', '1,100'],
    'Join Date': ['2023-01-15', '15/02/2023', '2023/03/10', 'April 5 2023', '2023-01-15', '2023-06-20', '01-07-2023'],
    'Status': ['Active', 'active', 'INACTIVE', 'Active', 'Active', 'pending', 'Active']
}

df_messy = pd.DataFrame(data)

print("\nMessy Data (Before Cleaning):")
display(df_messy)

print("\n=== Step 2: Cleaning the Data ===")

df = df_messy.copy()

# 1. Clean Customer Name
df['Customer Name'] = df['Customer Name'].astype(str).str.strip().str.title()
df['Customer Name'] = df['Customer Name'].replace('Nan', 'Unknown')
df['Customer Name'] = df['Customer Name'].fillna('Unknown')

# 2. Clean Email
df['Email'] = df['Email'].astype(str).str.lower().str.strip()
df['Email'] = df['Email'].replace('alice@email', 'alice@email.com')
df['Email'] = df['Email'].replace('none', np.nan)

# 3. Clean Age
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Age'] = df['Age'].fillna(df['Age'].median())

# 4. Clean Purchase Amount
df['Purchase Amount'] = df['Purchase Amount'].astype(str).replace('[\$,]', '', regex=True)
df['Purchase Amount'] = pd.to_numeric(df['Purchase Amount'], errors='coerce')
df['Purchase Amount'] = df['Purchase Amount'].fillna(df['Purchase Amount'].median())

# 5. Clean Status
df['Status'] = df['Status'].astype(str).str.strip().str.title()

# 6. Remove exact duplicates
df = df.drop_duplicates()

print("\nCleaned Data (After Cleaning):")
display(df)

print("\n=== Step 3: Making it AI-Ready ===")

# Create AI-ready text column
df['AI_Text'] = (
    "Customer: " + df['Customer Name'] +
    " | Email: " + df['Email'].fillna('Not provided') +
    " | Age: " + df['Age'].astype(int).astype(str) +
    " | Purchase: $" + df['Purchase Amount'].round(2).astype(str) +
    " | Status: " + df['Status']
)

print("\nAI-Ready Version:")
display(df[['Customer Name', 'AI_Text']])

print("\n=== Cleaning Summary ===")
print(f"Original rows: {len(df_messy)}")
print(f"Cleaned rows: {len(df)}")
print("Missing values handled: Yes")
print("Duplicates removed: Yes")
print("AI-ready text column created: Yes")

=== Step 1: Creating a Messy Sample Dataset ===

Messy Data (Before Cleaning):

<>:49: SyntaxWarning: invalid escape sequence '\$'
<>:49: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipykernel_1087/248126938.py:49: SyntaxWarning: invalid escape sequence '\$'
  df['Purchase Amount'] = df['Purchase Amount'].astype(str).replace('[\$,]', '', regex=True)

  Customer Name           Email     Age Purchase Amount     Join Date    Status
0     John Doe   john@email.com      25       $1,200.50    2023-01-15    Active
1    jane smith  JANE@EMAIL.COM  thirty             850    15/02/2023    active
2  ALICE WONDER     alice@email      28        2,300.00    2023/03/10  INACTIVE
3         Bob     bob@email.com      35         unknown  April 5 2023    Active
4      John Doe  john@email.com      25          1200.5    2023-01-15    Active
5           NaN   test@test.com      40          950.75    2023-06-20   pending
6       Charlie            None      22           1,100    01-07-2023    Active

=== Step 2: Cleaning the Data ===

Cleaned Data (After Cleaning):

  Customer Name            Email   Age  Purchase Amount     Join Date    Status
0      John Doe   john@email.com  25.0          1200.50    2023-01-15    Active
1    Jane Smith   jane@email.com  26.5           850.00    15/02/2023    Active
2  Alice Wonder  alice@email.com  28.0          2300.00    2023/03/10  Inactive
3           Bob    bob@email.com  35.0          1150.25  April 5 2023    Active
5       Unknown    test@test.com  40.0           950.75    2023-06-20   Pending
6       Charlie              NaN  22.0          1100.00    01-07-2023    Active

=== Step 3: Making it AI-Ready ===

AI-Ready Version:

  Customer Name                                                                                           AI_Text
0      John Doe         Customer: John Doe | Email: john@email.com | Age: 25 | Purchase: $1200.5 | Status: Active
1    Jane Smith        Customer: Jane Smith | Email: jane@email.com | Age: 26 | Purchase: $850.0 | Status: Active
2  Alice Wonder  Customer: Alice Wonder | Email: alice@email.com | Age: 28 | Purchase: $2300.0 | Status: Inactive
3           Bob              Customer: Bob | Email: bob@email.com | Age: 35 | Purchase: $1150.25 | Status: Active
5       Unknown          Customer: Unknown | Email: test@test.com | Age: 40 | Purchase: $950.75 | Status: Pending
6       Charlie            Customer: Charlie | Email: Not provided | Age: 22 | Purchase: $1100.0 | Status: Active

=== Cleaning Summary ===
Original rows: 7
Cleaned rows: 6
Missing values handled: Yes
Duplicates removed: Yes
AI-ready text column created: Yes