In [5]:
# Messy Cafe Sales Data → Clean AI-Ready Data
# Portfolio Project by Sudhakar

import pandas as pd
import numpy as np
from IPython.display import display

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 100)

print("=== Step 1: Loading Real Messy Cafe Sales Data ===")

df_messy = pd.read_csv('dirty_cafe_sales.csv')

print("\nShape of original data:", df_messy.shape)
print("\nColumn names:", df_messy.columns.tolist())
print("\nMessy Data (First 8 rows):")
display(df_messy.head(8))

print("\nMissing values:")
print(df_messy.isnull().sum())

print("\n=== Step 2: Cleaning the Data ===")

df = df_messy.copy()

# Clean Item
if 'Item' in df.columns:
    df['Item'] = df['Item'].astype(str).str.strip().str.title()
    df['Item'] = df['Item'].replace(['Nan', 'None', 'nan', 'UNKNOWN', 'Unknown'], np.nan)
    df['Item'] = df['Item'].fillna('Unknown Item')

# Clean Quantity
if 'Quantity' in df.columns:
    df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
    df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

# Clean Price Per Unit
if 'Price Per Unit' in df.columns:
    df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
    df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].median())

# Clean Total Spent
if 'Total Spent' in df.columns:
    df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')
    df['Total Spent'] = df['Total Spent'].fillna(df['Total Spent'].median())

# Clean Payment Method
if 'Payment Method' in df.columns:
    df['Payment Method'] = df['Payment Method'].astype(str).str.strip().str.title()
    df['Payment Method'] = df['Payment Method'].replace(['Nan', 'None', 'nan', 'ERROR', 'Unknown'], 'Unknown')
    df['Payment Method'] = df['Payment Method'].fillna('Unknown')

# Clean Location
if 'Location' in df.columns:
    df['Location'] = df['Location'].astype(str).str.strip().str.title()
    df['Location'] = df['Location'].replace(['Nan', 'None', 'nan', 'UNKNOWN'], 'Unknown')
    df['Location'] = df['Location'].fillna('Unknown')

# Remove duplicates
df = df.drop_duplicates()

print("\nCleaned Data (First 8 rows):")
display(df.head(8))
print("\nShape after cleaning:", df.shape)

print("\n=== Step 3: Creating AI-Ready Version ===")

df['AI_Text'] = (
    "Item: " + df['Item'].astype(str) +
    " | Qty: " + df['Quantity'].astype(int).astype(str) +
    " | Price: $" + df['Price Per Unit'].round(2).astype(str) +
    " | Total: $" + df['Total Spent'].round(2).astype(str) +
    " | Payment: " + df['Payment Method'].astype(str) +
    " | Location: " + df['Location'].astype(str)
)

print("\nAI-Ready Sample:")
display(df[['Item', 'AI_Text']].head(8))

print("\n=== Cleaning Summary ===")
print(f"Original rows: {len(df_messy)}")
print(f"Cleaned rows: {len(df)}")
print("Missing values handled: Yes")
print("Duplicates removed: Yes")
print("AI-ready text column created: Yes")

=== Step 1: Loading Real Messy Cafe Sales Data ===

Shape of original data: (10000, 8)

Column names: ['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date']

Messy Data (First 8 rows):

  Transaction ID      Item Quantity Price Per Unit Total Spent  Payment Method  Location Transaction Date
0    TXN_1961373    Coffee        2            2.0         4.0     Credit Card  Takeaway       2023-09-08
1    TXN_4977031      Cake        4            3.0        12.0            Cash  In-store       2023-05-16
2    TXN_4271903    Cookie        4            1.0       ERROR     Credit Card  In-store       2023-07-19
3    TXN_7034554     Salad        2            5.0        10.0         UNKNOWN   UNKNOWN       2023-04-27
4    TXN_3160411    Coffee        2            2.0         4.0  Digital Wallet  In-store       2023-06-11
5    TXN_2602893  Smoothie        5            4.0        20.0     Credit Card       NaN       2023-03-31
6    TXN_4433211   UNKNOWN        3            3.0         9.0           ERROR  Takeaway       2023-10-06
7    TXN_6699534  Sandwich        4            4.0        16.0            Cash   UNKNOWN       2023-10-28

Missing values:
Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

=== Step 2: Cleaning the Data ===

Cleaned Data (First 8 rows):

  Transaction ID          Item  Quantity  Price Per Unit  Total Spent  Payment Method  Location Transaction Date
0    TXN_1961373        Coffee       2.0             2.0          4.0     Credit Card  Takeaway       2023-09-08
1    TXN_4977031          Cake       4.0             3.0         12.0            Cash  In-Store       2023-05-16
2    TXN_4271903        Cookie       4.0             1.0          8.0     Credit Card  In-Store       2023-07-19
3    TXN_7034554         Salad       2.0             5.0         10.0         Unknown   Unknown       2023-04-27
4    TXN_3160411        Coffee       2.0             2.0          4.0  Digital Wallet  In-Store       2023-06-11
5    TXN_2602893      Smoothie       5.0             4.0         20.0     Credit Card   Unknown       2023-03-31
6    TXN_4433211  Unknown Item       3.0             3.0          9.0           Error  Takeaway       2023-10-06
7    TXN_6699534      Sandwich       4.0             4.0         16.0            Cash   Unknown       2023-10-28

Shape after cleaning: (10000, 8)

=== Step 3: Creating AI-Ready Version ===

AI-Ready Sample:

           Item                                                                                           AI_Text
0        Coffee     Item: Coffee | Qty: 2 | Price: $2.0 | Total: $4.0 | Payment: Credit Card | Location: Takeaway
1          Cake             Item: Cake | Qty: 4 | Price: $3.0 | Total: $12.0 | Payment: Cash | Location: In-Store
2        Cookie     Item: Cookie | Qty: 4 | Price: $1.0 | Total: $8.0 | Payment: Credit Card | Location: In-Store
3         Salad          Item: Salad | Qty: 2 | Price: $5.0 | Total: $10.0 | Payment: Unknown | Location: Unknown
4        Coffee  Item: Coffee | Qty: 2 | Price: $2.0 | Total: $4.0 | Payment: Digital Wallet | Location: In-Store
5      Smoothie   Item: Smoothie | Qty: 5 | Price: $4.0 | Total: $20.0 | Payment: Credit Card | Location: Unknown
6  Unknown Item     Item: Unknown Item | Qty: 3 | Price: $3.0 | Total: $9.0 | Payment: Error | Location: Takeaway
7      Sandwich          Item: Sandwich | Qty: 4 | Price: $4.0 | Total: $16.0 | Payment: Cash | Location: Unknown

=== Cleaning Summary ===
Original rows: 10000
Cleaned rows: 10000
Missing values handled: Yes
Duplicates removed: Yes
AI-ready text column created: Yes